### ISSUE TITLE
pyfactxx.rdflib_interface

### ISSUE THREAD

**Issue by yelimkim24** [tilde-lab/pyfactxx#13]
What's wrong?

FaCT++.Kernel: Reasoner for the SROIQ(D) Description Logic, 64-bit
Copyright (C) Dmitry Tsarkov, Ivan Rygaev, 2002-2022. Version 1.8.1-SNAPSHOT (21 June 2022)
Traceback (most recent call last):
  File "./bin/factpp-load", line 24, in <module>
    import pyfactxx.rdflib_interface
ModuleNotFoundError: No module named 'pyfactxx.rdflib_interface'

**Comment by blokhin** [comment]
Hi @yelimkim24 this was an outdated code, which I have cleaned from a repo now. Please, update from `master` and try these examples:

```
python examples/imply-class.py
python examples/zebra-puzzle.py
python coras/examples/run_rdf.py examples/tsars_corr.rdf
```

You might also try some ontologies shipped in the `coras/integration` folder:

```
./coras/bin/coras-query coras/integration/foaf/01-foaf.sq coras/integration/foaf/foaf.rdf coras/integration/foaf/tbl-foaf-card.n3
./coras/bin/coras-query coras/integration/foaf/02-foaf.sq coras/integration/foaf/foaf.rdf coras/integration/foaf/tbl-foaf-card.n3
./coras/bin/coras-query coras/integration/foaf/03-foaf.sq coras/integration/foaf/foaf.rdf coras/integration/foaf/03-foaf-ex.n3
./coras/bin/coras-query coras/integration/tsars/01-tsars.sq coras/integration/tsars/tsars.rdf
./coras/bin/coras-query coras/integration/tsars/01-tsars.sq coras/examples/tsars_corr.rdf
```

I hope it will work for you now.
